name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]
       
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install libraries & tools (Linux)
      run: sudo apt update && sudo apt install curl libcurl4-openssl-dev
      if: matrix.os == 'ubuntu-latest'
      
    - name: Install libraries & tools (macOS)
      run: brew install curl automake
      if: matrix.os == 'macos-latest'
      
    - name: autoreconf
      run: autoreconf -i
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: autoreconf (Windows)
      run: C:\msys64\usr\bin\bash .github/windows-build.sh
      if: matrix.os == 'windows-latest'

    - name: configure (Windows)
      run: bash "./configure" --prefix=$(pwd)\build
      if: matrix.os == 'windows-latest'

    - name: configure
      run: ./configure --prefix=$(pwd)/build
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

    - name: make
      run: make

    - name: install
      run: make install
